routes/web.php
<?php

use App\Http\Controllers\Controller\AuthController;
use App\Http\Controllers\Controller\InteractiveFloorController;
use App\Http\Controllers\Controller\ProjectController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\View\InteractiveFloorController as ViewInteractiveFloorController;
use App\Http\Controllers\View\PageController;
use App\Http\Controllers\View\ProjectController as ViewProjectController;
use App\Http\Middleware\XFrameOptions;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home page
Route::get('/', [PageController::class,'home'])->name('home.index');
Route::get('/join', [ProjectController::class,'join'])->name('join');

// Auth page
Route::get('/register', [PageController::class,'register'])->name('register.index');
Route::get('/login', [PageController::class,'login'])->name('login.index');
Route::post('/register', [AuthController::class,'register'])->name('register.process');
Route::post('/login', [AuthController::class,'login'])->name('login.process');
Route::post('/logout',[AuthController::class,'logout'])->name('logout');

// Present page
Route::get('events/{eventCode}/present/{floorId?}',[ViewProjectController::class,'present'])
    ->name('interactiveFloor.present');
Route::get('events/{eventCode}/iframe/{floorId?}',[ViewProjectController::class,'iframe'])
    ->name('interactiveFloor.iframe')
    ->middleware(XFrameOptions::class);
Route::post('guestBook/{projectId}',[ProjectController::class,'saveGuestBook'])->name('guestBook');

Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard.index')->middleware('auth');

Route::prefix('interactive-floor')->name('interactiveFloor.')->middleware(['auth'])->group(function(){
    // Project
    Route::get('events',[ViewProjectController::class,'list'])->name('view.project.list');
    Route::get('events/{projectId}',[ViewProjectController::class,'detail'])->name('view.project.detail');
    Route::get('events/{projectId}/json',[ProjectController::class,'getProject'])->name('project.getProject');
    Route::get('events/{projectId}/present',[ViewProjectController::class,'present'])->name('project.present');
    Route::post('events',[ProjectController::class,'saveProject'])->name('project.saveProject');
    Route::delete('events/{projectId}',[ProjectController::class,'deleteProject'])->name('project.delete');
    Route::post('events/{projectId}/status/{status}',[ProjectController::class,'setStatus'])->name('project.setStatus');

    // Interactive Floor
    Route::get('events/{projectId}/interactiveFloor/create',[ViewInteractiveFloorController::class,'create'])->name('create');
    Route::get('events/{projectId}/interactiveFloor/{interactiveFloorId}',[ViewInteractiveFloorController::class,'detail'])->name('detail');
    Route::post('events/{projectId}/interactiveFloor',[InteractiveFloorController::class,'saveInteractiveFloor'])->name('save');
    Route::delete('events/{projectId}/interactiveFloor/{interactiveFloorId}',[InteractiveFloorController::class,'deleteInteractiveFloor'])->name('delete');

    // Info Box
    Route::post('events/{projectId}/interactiveFloor/{interactiveFloorId?}/saveInfoBox',[InteractiveFloorController::class,'saveInteractiveFloorInfoBox'])->name('save.infoBox');
    Route::get('events/{projectId}/interactiveFloor/{interactiveFloorId?}/infoBox/{infoBoxId?}',[InteractiveFloorController::class,'getInteractiveFloorInfoBox'])->name('detail.infoBox');
    Route::delete('events/{projectId}/interactiveFloor/{interactiveFloorId?}/infoBox/{infoBoxId?}',[InteractiveFloorController::class,'deleteInteractiveFloorInfoBox'])->name('delete.infoBox');
    Route::get('events/{projectId}/interactiveFloorDataTable',[InteractiveFloorController::class,'getDataTable'])->name('getDataTable');
});


// Helper 
Route::get('/sessionFlush', function(){
    session()->flush();
});

app/Models/InteractiveFloor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class InteractiveFloor extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'project_id',
        'title',
        'description',
        'main_image',
        'width',
        'height',
        'status',
        'remark',
    ];

    /**
     * Get the Project that owns the InteractiveFloor
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class, 'project_id', 'id');
    }

    /**
     * Get all of the interactiveFloorInfoBox for the InteractiveFloor
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function infoBox(): HasMany
    {
        return $this->hasMany(InteractiveFloorInfoBox::class, 'interactive_floor_id', 'id');
    }
}

app/Http/Controllers/Controller/InteractiveFloorController.php
<?php

namespace App\Http\Controllers\Controller;

use App\Http\Controllers\Controller;
use App\Models\InteractiveFloor;
use App\Models\InteractiveFloorInfoBox;
use App\Models\Tenant;
use App\Util\Constant;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Str;

class InteractiveFloorController extends Controller
{
    public function saveInteractiveFloor(Request $request,$projectId) {
        $Floor = InteractiveFloor::find($request->interactiveFloorId);
        if(empty($Floor)) {
            $Floor = new InteractiveFloor();
            $Floor->project_id = $projectId;
            $Floor->status = Constant::PUBLISH_STATUS_UNPUBLISH;
        }
        $formData = $request->only(['project_id','title','description']);
        $Floor->fill($formData);

        if($request->has('main_image') && !empty($request->main_image)) {
            $rules = [
                'main_image' => 'sometimes|mimes:jpeg,png,jpg,gif',
            ];
            $request->validate($rules);

            if(!empty($Floor->main_image)) {
                try {
                    unlink($Floor->main_image);
                } catch (\Throwable $th) {
                    Log::info($th);
                }
            }
            $file = $request->file('main_image');
            $fileName = date('YmdHis').$file->getClientOriginalName();
            $path = $file->storeAs('public/floor',$fileName);
            $Floor->main_image = 'public/storage/floor/'.$fileName;
        }

        if($Floor->save()) {
            return response()->json([
                'success' => true,
                'message' => __('api.data_saved',['name'=>'Interactive Floor']),
                'data'    => $Floor
            ],);
        }

        return response()->json([
            'success' => false,
            'message' => __('api.data_not_processed',['name'=>'Interactive Floor'])
        ]);
    }

    public function deleteInteractiveFloor(Request $request, $projectId, $interactiveFloorId) {
        $data = InteractiveFloor::find($interactiveFloorId);
        if(empty($data)) {
            throw new Exception(__('api.not_found',['name'=>'Interactive Floor']),404);
        }
        
        if($data->delete()) {
            return response()->json([
                'success' => true,
                'message' => __('api.data_deleted',['name'=>'Interactive Floor']),
            ],201);
        }

        return response()->json([
            'success' => false,
            'message' => __('api.data_not_processed',['name'=>'Interactive Floor'])
        ]);
    }

    public function saveInteractiveFloorInfoBox(Request $request, $projectId,$interactiveFloorId) {
        // test response
        // return response()->json(['data'=>$request->all()]);
        $InfoBox = InteractiveFloorInfoBox::find($request->id);
        if(empty($InfoBox)) {
            $InfoBox = new InteractiveFloorInfoBox();
            $InfoBox->interactive_floor_id = $interactiveFloorId;
        }
        $formData = $request->only(['pos_x','pos_y','title','size','price','description','remark','external_link']);
        $InfoBox->fill($formData);

        if(!empty($request->image)) {
            $rules = [
                'images' => 'sometimes|mimes:jpeg,png,jpg,gif',
            ];
            $request->validate($rules);

            if(!empty($InfoBox->images)) {
                try {
                    unlink($InfoBox->images);
                } catch (\Throwable $th) {
                    Log::info($th);
                }
            }
            $file = $request->file('image');
            $fileName = date('YmdHis').$file->getClientOriginalName();
            $path = $file->storeAs('public/infobox',$fileName);
            $InfoBox->images = 'public/storage/infobox/'.$fileName;
        }

        $InfoBox->status = (!empty($request->sold) && @$request->sold == 1) ? Constant::BOOTH_STATUS_SOLD : Constant::BOOTH_STATUS_NEW;

        if($InfoBox->save()) {
            // DB::statement("UPDATE interactive_floors SET width = $request->width, height = $request->height WHERE id = $request->interactive_floor_id; ");
            DB::table('interactive_floors')->where('id',$request->interactive_floor_id)->update(['width'=>$request->mainImgWidth,'height'=>$request->mainImgHeight]);
            if(!empty($request->sold) && @$request->sold == 1) {
                $tenant = Tenant::find($request->tenant_id);
                if(empty($tenant)) {
                    $tenant = new Tenant();
                    $tenant->infobox_id = $InfoBox->id;
                }
                $tenant->name = $request->tenant_name;
                $tenant->description = $request->tenant_description;
                $tenant->external_link = $request->tenant_ext_link;
                if(!empty($request->tenant_image)) {
                    $rules = [
                        'tenant_image' => 'sometimes|mimes:jpeg,png,jpg,gif',
                    ];
                    $request->validate($rules);
        
                    if(!empty($tenant->tenant_image)) {
                        try {
                            unlink($tenant->tenant_image);
                        } catch (\Throwable $th) {
                            Log::info($th);
                        }
                    }
                    $file = $request->file('tenant_image');
                    $fileName = date('YmdHis').$file->getClientOriginalName();
                    $path = $file->storeAs('public/tenant',$fileName);
                    $tenant->logo = 'public/storage/tenant/'.$fileName;
                }
                $tenant->save();
            }
            return response()->json([
                'success' => true,
                'message' => __('api.data_saved',['name'=>'Interactive Floor Info Box']),
                'data'    => $InfoBox
            ],);
        }

        return response()->json([
            'success' => false,
            'message' => __('api.data_not_processed',['name'=>'Interactive Floor Info Box'])
        ]);
    }

    public function getInteractiveFloorInfoBox($projectId,$interactiveFloorId,$infoBoxId) {
        $data = InteractiveFloorInfoBox::with('tenant')->find($infoBoxId);
        if(empty($data)) {
            throw new Exception(__('api.not_found',['name'=>'Info Box']),404);
        }
        return $data;
    }

    public function deleteInteractiveFloorInfoBox($projectId,$interactiveFloorId,$infoBoxId) {
        $data = InteractiveFloorInfoBox::find($infoBoxId);
        if(empty($data)) {
            throw new Exception(__('api.not_found',['name'=>'Info Box']),404);
        }
        if($data->delete()) {
            return response()->json([
                'success' => true,
                'message' => __('api.data_saved',['name'=>'Info Box']),
            ]);
        } else {
            return response()->json([
                'success' => false,
                'message' => __('api.data_not_processed',['name'=>'Info Box'])
            ]);
        }
    }

    public function getDataTable(Request $request, $projectId) {
        $datas = InteractiveFloor::with('project')->where('project_id',$projectId)->get();
        return DataTables::of($datas)
            ->addIndexColumn()
            ->addColumn('action',function($data){
                return '<a href="'.route('interactiveFloor.detail',['projectId'=>$data->project_id,'interactiveFloorId'=>$data->id]).'" class="btn btn-sm text-info btn-icon item-edit"><i class="bx bxs-pencil"></i></a>'.
                '<a href="javascript:;" onclick="deleteFloor('.$data->id.')" class="btn btn-sm text-danger btn-icon item-edit"><i class="bx bxs-trash"></i></a>'.
                '<a href="javascript:;" onclick="shareFloor(
                    \''.$data->title.'\',
                    \''.route('interactiveFloor.present', ['eventCode' => $data->project->code,'floorId'=>$data->id]).'\',
                    \''.route('interactiveFloor.iframe', ['eventCode' => $data->project->code,'floorId'=>$data->id]).'\',
                )" class="btn btn-sm text-info btn-icon item-edit"><i class="bx bxs-share"></i></a>';
            })
            ->escapeColumns([])->make(true);
    }
}

app/Http/Controllers/View/InteractiveFloorController.php
<?php

namespace App\Http\Controllers\view;

use App\Http\Controllers\Controller;
use App\Models\InteractiveFloor;
use App\Models\Project;
use Illuminate\Http\Request;

class InteractiveFloorController extends Controller
{
    public function create($projectId) 
    {
        $data['sidebar'] = 'projectList';
        $data['projectId'] = $projectId;
        $data['project'] = Project::find($projectId);
        $data['interactiveFloorData'] = InteractiveFloor::class;
        return view('pages.interactive-floor.main-form',$data);
    }
    public function detail($projectId,$interactiveFloorId)
    {
        $data['sidebar'] = 'projectList';
        $data['projectId'] = $projectId;
        $data['interactiveFloorData'] = InteractiveFloor::with(['project','infoBox.tenant'])->where('id',$interactiveFloorId)->first() ?? abort('404');
        return view('pages.interactive-floor.main-form',$data);
    }
}

resources/views/pages/interactive-floor/list.blade.php
@extends('layouts.base')
@section('title', 'Interactive Floor')
@push('customCSS')
    <!-- Datatable css -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/responsive.bootstrap5.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/datatables.checkboxes.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/buttons.bootstrap5.css') }}">
@endpush
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">
            <span class="muted fw-light">Interactive Floor/</span> Daftar Interactive Floor
        </h4>
        <div class="row">
            <div class="col-lg-12 mb-4 order-0">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-primary">Daftar Interactive Floor</h5>
                        <div class="card-datatable table-responsive text-nowrap pt-0">
                            <table class="datatables-basic table border-top">
                                <thead>
                                    <tr>
                                        <th>id</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Date</th>
                                        <th>Salary</th>
                                        <th>Status</th>
                                        {{-- <th>Action</th> --}}
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('customJS')
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/jquery.dataTables.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables-bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables.responsive.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/responsive.bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables.checkboxes.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables-buttons.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.html5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.print.js') }}"></script>
        {{-- <script src="{{ asset('assets/js/docs-tables-datatables.js') }}"></script> --}}
        <script>
            $(function() {

                'use strict';

                var dt_basic_table = $('.datatables-basic');
                dt_basic_table.DataTable({
                    'processing': true,
                    'serverSide': true,
                    'language': {
                        processing: '<i class="fa fa-spinner fa-spin fa-2x fa-fw" style="color:#07a7e1"></i><span class="sr-only">Loading...</span> '
                    },
                    'ajax': {
                        url: "{{asset('assets/json/table-datatable.json')}}",
                    },
                    'dataType': 'json',
                    'searching': true,
                    'paging': true,
                    'lengthChange': true,
                    'columns': [
                        { data: 'id', name: 'id'},
                        { data: 'full_name', name: 'full_name'},
                        { data: 'email', name: 'email'},
                        { data: 'start_date', name: 'start_date'},
                        { data: 'salary', name: 'salary'},
                        { data: 'status', name: 'status'},
                        // { data: '', name: ''},
                    ],
                    'info': true,
                    'autoWidth': false
                });
            });
        </script>
    @endpush
@endsection

resources/views/pages/interactive-floor/project-detail.blade.php
@extends('layouts.base')
@section('title', 'Interactive Floor')
@push('customCSS')
    <!-- Datatable css -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/responsive.bootstrap5.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/datatables.checkboxes.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/buttons.bootstrap5.css') }}">
@endpush
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-2">
            <span class="muted fw-light">Interactive Floor/</span>
            <span class="muted fw-light"><a class="text-secondary text-decoration-underline"
                    href="{{ route('interactiveFloor.view.project.list') }}">Event Saya</a>/</span>
            <span class="event-title">{{ $projectData->title }}</span> <a href="javascript:;"
                onclick="editProject({{ $projectData->id }})"><span class="tf-icons bx bx-pencil"></span></a>
        </h4>
        <h5 class="mb-2">
            kode unik: {{ $projectData->code }}
            <a href="{{ route('interactiveFloor.present', ['eventCode' => $projectData->code]) }}" target="_blank"><i
                    class="bx bx-share-alt bx-xs text-primary" data-bs-toggle="tooltip" data-bs-offset="0,4"
                    data-bs-placement="top" data-bs-html="true" title="" data-bs-original-title="Tampilkan"></i></a>
        </h5>
        <div class="row">
            <div class="col-lg-12 mb-4 order-0">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <h5 class="card-title">
                                    <a href="{{ route('interactiveFloor.view.project.list') }}" class="text-secondary"><i
                                            class="bx bx-chevron-left bx-sm"></i></a>
                                    Daftar Interactive Floor (IF) <span
                                        class="event-title">{{ $projectData->title }}</span>
                                </h5>
                            </div>
                            <div class="col-md-3">
                                <div class="form-check form-switch mb-2 text-right">
                                    <input class="form-check-input" type="checkbox" id="tayang" name="tayang"
                                        value="1" onchange="setStatus()"
                                        @if ($projectData->status == \App\Util\Constant::PUBLISH_STATUS_PUBLISHED) checked @endif />
                                    <label class="form-check-label" for="tayang"><strong>Tayangkan ke
                                            publik</strong></label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="text-end">
                                    <a href="{{ route('interactiveFloor.create', ['projectId' => $projectData->id]) }}"
                                        class="btn btn-icon btn-primary">
                                        <span class="bx bx-plus"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-datatable table-responsive text-nowrap pt-0">
                            <table class="datatables-basic table border-top">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama IF</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('pages.interactive-floor.part.modal-share-floor')
    @push('customJS')
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/jquery.dataTables.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables-bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables.responsive.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/responsive.bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables.checkboxes.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/datatables-buttons.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.bootstrap5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.html5.js') }}"></script>
        <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/buttons.print.js') }}"></script>
        {{-- <script src="{{ asset('assets/js/docs-tables-datatables.js') }}"></script> --}}

        <script>
            let datatableUrl = "{{ route('interactiveFloor.getDataTable', ['projectId' => $projectData->id]) }}";

            var dt_basic_table = $('.datatables-basic');
            dt_basic_table.DataTable({
                'processing': true,
                'serverSide': true,
                'language': {
                    processing: '<i class="fa fa-spinner fa-spin fa-2x fa-fw" style="color:#07a7e1"></i><span class="sr-only">Loading...</span> '
                },
                'ajax': {
                    url: datatableUrl,
                },
                'dataType': 'json',
                'searching': true,
                'paging': true,
                'lengthChange': true,
                'columns': [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
                'info': true,
                'autoWidth': false
            });


            function editProject(id) {
                let url = "{{ route('interactiveFloor.project.getProject', ['projectId' => ':id']) }}";
                url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    type: "GET",
                    success: function(response) {
                        $('#modalCreateProject .modal-title').text('Detail Event');
                        $('#modalCreateProject form')[0].reset();
                        $('#modalCreateProject form [name="projectId"]').val(response.id);
                        $('#modalCreateProject form img').attr('src','{{url('')}}/'+response.logo);
                        $('#modalCreateProject form [name="title"]').val(response.title);
                        $('#modalCreateProject form [name="description"]').val(response.description);
                        $('#modalCreateProject').modal('show');
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        swal({
                            title: 'System Error',
                            text: errorThrown,
                            icon: 'error',
                            timer: '3000'
                        });
                    }
                });
            }

            function setStatus() {
                console.log($('[name="tayang"]').prop("checked"));
                let status = '';
                $('[name="tayang"]').prop("checked") ? status = '{{ \App\Util\Constant::PUBLISH_STATUS_PUBLISHED }}' : status =
                    '{{ \App\Util\Constant::PUBLISH_STATUS_UNPUBLISH }}';
                let url =
                    "{{ route('interactiveFloor.project.setStatus', ['projectId' => $projectData->id, 'status' => ':status']) }}";
                url = url.replace(':status', status);
                $.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        _token: '{{ csrf_token() }}',
                    },
                    success: function(response) {
                        swal({
                            title: 'Berhasil',
                            text: response.message,
                            icon: 'success',
                            timer: '3000'
                        });
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        swal({
                            title: 'System Error',
                            text: errorThrown,
                            icon: 'error',
                            timer: '3000'
                        });
                    }
                });
            }

            function deleteFloor(id) {
                swal({
                    title: "Yakin Hapus Interactive Floor?",
                    text: "Data akan dihapus permanen",
                    icon: "warning",
                    buttons: {
                        cancel: true,
                        confirm: {
                            text: 'Hapus!',
                            closeModal: false,
                        },
                    },
                }).then((process) => {
                    if (process) {
                        let url =
                            "{{ route('interactiveFloor.delete', ['projectId' => $projectData->id, 'interactiveFloorId' => ':id']) }}";
                        url = url.replace(':id', id);
                        $.ajax({
                            url: url,
                            type: "DELETE",
                            data: {
                                '_token': "{{ csrf_token() }}"
                            },
                            success: function(response) {
                                swal({
                                    title: 'Berhasil',
                                    text: response.message,
                                    icon: 'success',
                                    timer: '3000'
                                }).then(() => {
                                    location.reload()
                                });
                            },
                            error: function(jqXHR, textStatus, errorThrown) {
                                swal({
                                    title: 'System Error',
                                    text: errorThrown,
                                    icon: 'error',
                                    timer: '3000'
                                });
                            }
                        });
                    }
                })

            }

            function shareFloor(title,link,iframe) {
                $('#modalShareFloor .modal-title').text(title);
                $('#modalShareFloor [name="share_link"]').val(link);
                let iFrameHTML = '<iframe src="'+iframe+'" frameborder="0" width="" height=""></iframe>'
                $('#modalShareFloor [name="share_iframe"]').val(iFrameHTML);
                $('#modalShareFloor').modal('show');
            }
        </script>
    @endpush
@endsection