routes/web.php
<?php

use App\Http\Controllers\Controller\AuthController;
use App\Http\Controllers\Controller\InteractiveFloorController;
use App\Http\Controllers\Controller\ProjectController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\View\InteractiveFloorController as ViewInteractiveFloorController;
use App\Http\Controllers\View\PageController;
use App\Http\Controllers\View\ProjectController as ViewProjectController;
use App\Http\Middleware\XFrameOptions;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home page
Route::get('/', [PageController::class,'home'])->name('home.index');
Route::get('/join', [ProjectController::class,'join'])->name('join');

// Auth page
Route::get('/register', [PageController::class,'register'])->name('register.index');
Route::get('/login', [PageController::class,'login'])->name('login.index');
Route::post('/register', [AuthController::class,'register'])->name('register.process');
Route::post('/login', [AuthController::class,'login'])->name('login.process');
Route::post('/logout',[AuthController::class,'logout'])->name('logout');

// Present page
Route::get('events/{eventCode}/present/{floorId?}',[ViewProjectController::class,'present'])
    ->name('interactiveFloor.present');
Route::get('events/{eventCode}/iframe/{floorId?}',[ViewProjectController::class,'iframe'])
    ->name('interactiveFloor.iframe')
    ->middleware(XFrameOptions::class);
Route::post('guestBook/{projectId}',[ProjectController::class,'saveGuestBook'])->name('guestBook');

Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard.index')->middleware('auth');

Route::prefix('interactive-floor')->name('interactiveFloor.')->middleware(['auth'])->group(function(){
    // Project
    Route::get('events',[ViewProjectController::class,'list'])->name('view.project.list');
    Route::get('events/{projectId}',[ViewProjectController::class,'detail'])->name('view.project.detail');
    Route::get('events/{projectId}/json',[ProjectController::class,'getProject'])->name('project.getProject');
    Route::get('events/{projectId}/present',[ViewProjectController::class,'present'])->name('project.present');
    Route::post('events',[ProjectController::class,'saveProject'])->name('project.saveProject');
    Route::delete('events/{projectId}',[ProjectController::class,'deleteProject'])->name('project.delete');
    Route::post('events/{projectId}/status/{status}',[ProjectController::class,'setStatus'])->name('project.setStatus');

    // Interactive Floor
    Route::get('events/{projectId}/interactiveFloor/create',[ViewInteractiveFloorController::class,'create'])->name('create');
    Route::get('events/{projectId}/interactiveFloor/{interactiveFloorId}',[ViewInteractiveFloorController::class,'detail'])->name('detail');
    Route::post('events/{projectId}/interactiveFloor',[InteractiveFloorController::class,'saveInteractiveFloor'])->name('save');
    Route::delete('events/{projectId}/interactiveFloor/{interactiveFloorId}',[InteractiveFloorController::class,'deleteInteractiveFloor'])->name('delete');

    // Info Box
    Route::post('events/{projectId}/interactiveFloor/{interactiveFloorId?}/saveInfoBox',[InteractiveFloorController::class,'saveInteractiveFloorInfoBox'])->name('save.infoBox');
    Route::get('events/{projectId}/interactiveFloor/{interactiveFloorId?}/infoBox/{infoBoxId?}',[InteractiveFloorController::class,'getInteractiveFloorInfoBox'])->name('detail.infoBox');
    Route::delete('events/{projectId}/interactiveFloor/{interactiveFloorId?}/infoBox/{infoBoxId?}',[InteractiveFloorController::class,'deleteInteractiveFloorInfoBox'])->name('delete.infoBox');
    Route::get('events/{projectId}/interactiveFloorDataTable',[InteractiveFloorController::class,'getDataTable'])->name('getDataTable');
});


// Helper 
Route::get('/sessionFlush', function(){
    session()->flush();
});

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default"
    data-assets-path="../assets/" data-template="vertical-menu-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>@yield('title') | Presentasee</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{{ asset('assets/img/favicon/about-image.3b353a9a.png') }}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/fonts/boxicons.css') }}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/css/core.css') }}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{{ asset('assets/vendor/css/theme-default.css') }}"
        class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{{ asset('assets/css/demo.css') }}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/sweetalert/sweetalert.css') }}" />

    <link rel="stylesheet" href="{{ asset('assets/vendor/libs/apex-charts/apex-charts.css') }}" />

    {{-- Custom CSS --}}
    <link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}" />

    <!-- Page CSS -->

    @stack('customCSS')

    <!-- Helpers -->
    <script src="{{ asset('assets/vendor/js/helpers.js') }}"></script>

    <script src="{{ asset('assets/js/config.js') }}"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a href="#" class="app-brand-link">
                        <span class="app-brand-logo demo">
                            <img src="{{asset('assets/img/favicon/about-image.3b353a9a.png')}}" alt="" srcset="" width="35px">
                        </span>
                        <span class="app-brand-text demo menu-text fw-bolder ms-2">Presentasee</span>
                    </a>

                    <a href="javascript:void(0);"
                        class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                @include('layouts.sidebar')
            </aside>
            <!-- / Menu -->

            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->
                @include('layouts.navbar')
                <!-- / Navbar -->

                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->
                    @yield('content')
                    <!-- / Content -->

                    <!-- Basic footer -->
                    <section id="basic-footer">
                        <footer class="footer bg-light">
                            <div
                                class="container-fluid d-flex flex-md-row flex-column justify-content-between align-items-md-center gap-1 container-p-x py-3">
                                <div>
                                    <a href="https://presentasee.com" target="_blank"
                                        class="footer-text fw-bolder">Presentasee</a>
                                    ©
                                </div>
                                <div>
                                    <a href="https://themeselection.com/license/" class="footer-link me-4"
                                        target="_blank">License</a>
                                    <a href="javascript:void(0)" class="footer-link me-4">Help</a>
                                    <a href="javascript:void(0)" class="footer-link me-4">Contact</a>
                                    <a href="javascript:void(0)" class="footer-link">Terms &amp; Conditions</a>
                                </div>
                            </div>
                        </footer>
                    </section>
                    <!--/ Basic footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    <div class="buy-now">
        <a href="#" target="_blank" class="btn btn-danger btn-buy-now">Beralih ke Pro</a>
    </div>
    @include('pages.interactive-floor.part.modal-create-project')

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{{ asset('assets/vendor/libs/jquery/jquery.js') }}"></script>
    <script src="{{ asset('assets/vendor/libs/popper/popper.js') }}"></script>
    <script src="{{ asset('assets/vendor/js/bootstrap.js') }}"></script>
    <script src="{{ asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js') }}"></script>

    <script src="{{ asset('assets/vendor/js/menu.js') }}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="{{ asset('assets/vendor/libs/apex-charts/apexcharts.js') }}"></script>
    <script src="{{ asset('assets/vendor/libs/sweetalert/sweetalert.min.js') }}"></script>

    <!-- Main JS -->
    <script src="{{ asset('assets/js/main.js') }}"></script>

    <!-- Page JS -->
    <script src="{{ asset('assets/js/dashboards-analytics.js') }}"></script>
    <script src="{{ asset('assets/js/ui-toasts.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("body").tooltip({ selector: '[data-bs-toggle=tooltip]' });
        });
        
        function renderError(response) {
            for(key in response) {
                $('#error-'+key).text(response[key]);
            }
        }

        function resetError() {
            $('.error').text('');
        }

        function addProject() {
            $('#modalCreateProject .modal-title').text('Detail Event');
            $('#modalCreateProject form')[0].reset();
            $('#modalCreateProject form [name="projectId"]').val('');
            $('#modalCreateProject').modal('show');
        }

        function saveProject() {
            resetError();
            $.ajax({
                url: "{{ route('interactiveFloor.project.saveProject') }}",
                type: "POST",
                data: new FormData($('#formProject')[0]),
                contentType: false,
                processData: false,
                success: function(response) {
                    if (response.success) {
                        swal({
                            title: 'Berhasil',
                            text: response.message,
                            icon: 'success',
                            timer: '3000'
                        });
                        if($('#modalCreateProject [name="projectId"]').value) {
                            $('.event-title').text(response.data.title);
                        } else {
                            // redirect to detail page if create new
                            let urlRedirect = "{{route('interactiveFloor.view.project.detail',['projectId'=>':id'])}}";
                            urlRedirect = urlRedirect.replace(':id',response.data.id);
                            location.href = urlRedirect;
                        }
                        $('#modalCreateProject').modal('hide');
                    } else {
                        swal({
                            title: 'Gagal',
                            text: response.message,
                            icon: 'error',
                            timer: '3000'
                        });
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    let title = 'Server Error';
                    let text = errorThrown;
                    if(jqXHR.responseJSON.errors) {
                        title = 'Gagal';
                        text = 'Periksa data kembali';
                    }
                    swal({
                        title: title,
                        text: text,
                        icon: 'error',
                        timer: '3000'
                    }).then(()=>{
                        if(jqXHR.responseJSON.errors) {
                            renderError(jqXHR.responseJSON.errors)
                        }
                    });
                }
            });
        }
    </script>

    @stack('customJS')

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

resources/views/layouts/navbar.blade.php
<div class="container">
    <ul class="navbar-nav float-end flex-row align-items-center ms-auto mt-3 ">
        <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
            <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
            </a>
        </div>
        <!-- Place this tag where you want the button to render. -->
        <li class="nav-item lh-1 me-3 ">
            <button type="button" class="btn btn-icon btn-secondary">
                <span class="tf-icons bx bx-bell"></span>
            </button>
        </li>
        <!-- User -->
        <li class="nav-item navbar-dropdown dropdown-user dropdown">
            <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                <div class="avatar avatar-online">
                    <div id="profile-image">{{\Auth::user()->name[0]}}</div>
                    {{-- <img src="{{asset('assets/img/avatars/1.png')}}" alt class="w-px-40 h-auto rounded-circle" /> --}}
                </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
                <li>
                    <a class="dropdown-item" href="#">
                        <div class="d-flex">
                            <div class="flex-shrink-0 me-3">
                                <div class="avatar avatar-online">
                                    <div id="profile-image">{{\Auth::user()->name[0]}}</div>
                                    {{-- <img src="{{asset('assets/img/avatars/1.png')}}" alt class="w-px-40 h-auto rounded-circle" /> --}}
                                </div>
                            </div>
                            <div class="flex-grow-1">
                                <span class="fw-semibold d-block">{{\Auth::user()->name}}</span>
                                <small class="text-muted">Basic</small>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <div class="dropdown-divider"></div>
                </li>
                {{-- <li>
                    <a class="dropdown-item" href="#">
                        <i class="bx bx-user me-2"></i>
                        <span class="align-middle">My Profile</span>
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">
                        <i class="bx bx-cog me-2"></i>
                        <span class="align-middle">Settings</span>
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">
                        <span class="d-flex align-items-center align-middle">
                            <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                            <span class="flex-grow-1 align-middle">Billing</span>
                            <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
                        </span>
                    </a>
                </li> --}}
                {{-- <li>
                    <div class="dropdown-divider"></div>
                </li> --}}
                <li>
                    <a class="dropdown-item" href="{{route('logout')}}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                    </a>
                    <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </li>
        <!--/ User -->
    </ul>
</div>

resources/views/layouts/sidebar.blade.php
<ul class="menu-inner py-1">
    <!-- Dashboard -->
    <li class="menu-item @if($sidebar == 'dashboard') active @endif">
        <a href="{{route('dashboard.index')}}" class="menu-link">
            <i class="menu-icon tf-icons bx bx-home-circle"></i>
            <div data-i18n="Analytics">Dasbor</div>
        </a>
    </li>

    <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Interactive Floor Plan</span>
    </li>
    <li class="menu-item">
        <a href="javascript:;" onclick="addProject()" class="menu-link">
            <i class="menu-icon tf-icons bx bx-plus"></i>
            <div data-i18n="Basic">Buat baru</div>
        </a>
    </li>
    <li class="menu-item @if($sidebar == 'projectList') active @endif">
        <a href="{{route('interactiveFloor.view.project.list')}}" class="menu-link">
            <i class="menu-icon tf-icons bx bx-collection"></i>
            <div data-i18n="Basic">Event Saya</div>
        </a>
    </li>
    
    <li class="menu-header small text-uppercase"><span class="menu-header-text">Interactive Slide</span></li>
    <li class="menu-item">
        <a href="javascript:;" class="menu-link">
            <i class="menu-icon tf-icons bx bx-collection"></i>
            <div data-i18n="Basic">Coming Soon..</div>
        </a>
    </li>

    {{-- <li class="menu-header small text-uppercase"><span class="menu-header-text">Akun</span></li>
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
            <i class="menu-icon tf-icons bx bx-dock-top"></i>
            <div data-i18n="Account Settings">pengaturan</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="pages-account-settings-account.html" class="menu-link">
                    <div data-i18n="Account">Account</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="pages-account-settings-notifications.html" class="menu-link">
                    <div data-i18n="Notifications">Notifications</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="pages-account-settings-connections.html" class="menu-link">
                    <div data-i18n="Connections">Connections</div>
                </a>
            </li>
        </ul>
    </li>
    <li class="menu-item">
        <a href="#" class="menu-link">
            <i class="menu-icon tf-icons bx bx-power-off"></i>
            <div data-i18n="Basic">Keluar</div>
        </a>
    </li> --}}
</ul>